controllers/AjaxController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;

class AjaxController extends Controller {

	public $enableCsrfValidation = false;
	public $layout = 'ajax';

	public function actions() {
		return [
			'error'   => [
				'class' => 'yii\web\ErrorAction',
			],
		];
	}

	public function actionSendEmail() {
		$success = false;
		if ($params = Yii::$app->request->post()) {
			$success = Yii::$app->mailer
				->compose('@views/mail/common', [
					'name'  => $params['name'],
					'phone' => $params['phone']
				])
				->setFrom(Yii::$app->params['emailFrom'])
				->setTo(Yii::$app->params['emailTo'])
				->setSubject('Заказ звонка с сайта ' . Yii::$app->name)
				->send();
		}

		echo (int) $success;
	}
}

views/_parts/button-back.php
<div class="pin-to-bottom">
	<a class="arrowed-link__back text-horizontal-arrow_green" href="#" onclick="history.back(); return false;">
		<span class="arrowed-link__arrow arrowed-link__arrow_60 arrowed-link__arrow_left"></span>
		Назад
	</a>
</div>

views/_parts/contacts.php
<div class="contacts">
	<span class="contacts__item">
		<a href="mailto:salon@formsvl.ru">salon@formsvl.ru</a>
	</span>
	<span class="contacts__item contacts__item_whatsapp">
		+7 914 000 00 00
	</span>
</div>

views/_parts/form-callback.php
<?php
/**
 * @var string $additionalClass
 * @var string $style
 */

$additionalClass = isset($additionalClass)? " $additionalClass": '';
$class = isset($style)? " form-callback_{$style}": '';
?>

<form action="<?= \yii\helpers\Url::to(['ajax/send-email']) ?>" class="js-ajax-submit form-callback<?= $class . $additionalClass ?>" method="post">
	<div class="row">
		<div class="col-sm-6 form-group">
			<input class="form-control form-callback__text" type="text" name="phone" placeholder="Телефон" required>
		</div>
		<div class="col-sm-6 form-group">
			<input class="form-control form-callback__text" type="text" name="name" placeholder="Имя">
		</div>
	</div>

	<button class="btn btn-summary form-callback__button">Заказать звонок</button>
</form>

views/_parts/furniture-ready-paged.php
<?php
/**
 * Pagination for intro pages
 *
 * @var \yii\web\View $this
 */

$menu = [
	['main/furniture-ready-paged'],
	['main/furniture-ready-paged-about'],
];

echo $this->render('@parts/pagination', [
	'menu' => $menu,
]);

views/_parts/furniture-ready.php
<?php
/**
 * Pagination for intro pages
 *
 * @var \yii\web\View $this
 */

$menu = [
	['main/furniture-ready'],
	['main/furniture-ready-about'],
];

echo $this->render('@parts/pagination', [
	'menu' => $menu,
]);

views/_parts/order-fitting.php
<a href="#" class="order-fitting"
   data-toggle="modal" data-target="#orderFitting">
	<span title="Заказать&nbsp;примерку&nbsp;мебели" data-toggle="tooltip" data-placement="top" class="order-fitting__tooltip">
	</span>
</a>

<div class="modal fade" id="orderFitting">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
						aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">Заказать примерку мебели</h4>
			</div>
			<div class="modal-body">
				<form action="<?= \yii\helpers\Url::to(['ajax/send-email']) ?>" class="js-ajax-submit form-callback form-callback_green">
					<div class="row">
						<div class="col-sm-6 form-group">
							<input class="form-control form-callback__text" type="text" name="phone" placeholder="Телефон">
						</div>
						<div class="col-sm-6 form-group">
							<input class="form-control form-callback__text" type="text" name="name" placeholder="Имя">
						</div>
					</div>

					<button class="btn btn-summary form-callback__button">Заказать</button>
				</form>
			</div>
		</div>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div><!-- /.modal -->

views/_parts/pagination-furniture-order.php
<?php
/**
 * Pagination for intro pages
 *
 * @var \yii\web\View $this
 */

$menu = [
	['main/furniture-order'],
	['main/furniture-order-about'],
];

echo $this->render('@parts/pagination', [
	'menu' => $menu,
]);

views/_parts/pagination-furniture-ready-cilek.php
<?php
/**
 * Pagination for intro pages
 *
 * @var \yii\web\View $this
 */

$menu = [
	['main/furniture-ready-cilek'],
	['main/furniture-ready-cilek-about'],
	['main/furniture-ready-cilek-map'],
	['main/furniture-ready-cilek-years'],
	['main/furniture-ready-tct-nanotec'],
];

echo $this->render('@parts/pagination', [
	'menu' => $menu,
]);

views/_parts/pagination-intro.php
<?php
/**
 * Pagination for intro pages
 *
 * @var \yii\web\View $this
 */

$menu = [
	['main/index'],
	['main/catalog'],
	['main/benefits'],
	['main/what-to-know'],
	['main/about'],
	['main/how-we-work'],
];

echo $this->render('@parts/pagination', [
	'menu'   => $menu,
]);

views/_parts/pagination-kitchens.php
<?php
/**
 * Pagination for intro pages
 *
 * @var \yii\web\View $this
 */

$menu = [
	['main/kitchens-pdf'],
	['main/kitchens-intro'],
	['main/kitchens-benefits'],
	['main/kitchens-tv'],
	['main/kitchens-map'],
];

echo $this->render('@parts/pagination', [
	'menu'   => $menu,
]);

views/_parts/pagination-sits.php
<?php
/**
 * Pagination for intro pages
 *
 * @var \yii\web\View $this
 */

$menu = [
	['main/sits'],
	['main/sits-about'],
];

echo $this->render('@parts/pagination', [
	'menu' => $menu,
]);

views/_parts/pagination.php
<?php
/**
 * Pagination for intro pages
 *
 *
 * @var array $menu
 */

use yii\helpers\Html;
?>

<ul class="pagination">
	<?php foreach ($menu as $url) {
		echo Html::tag('li', Html::a('', $url), (Yii::$app->controller->route == $url[0]? ['class' => 'active']: []));
	} ?>
</ul>