controllers/MainController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use Swift_Attachment;

class MainController extends Controller {

	public $enableCsrfValidation = false;

	public function beforeAction($action) {
		if (!parent::beforeAction($action)) {
			return false;
		}

		if (Yii::$app->request->isAjax) {
			$this->layout = 'ajax';
		}
		return true;
	}

	public function behaviors() {
		return [
			'access' => [
				'class' => AccessControl::className(),
				'only'  => ['logout'],
				'rules' => [
					[
						'actions' => ['logout'],
						'allow'   => true,
						'roles'   => ['@'],
					],
				],
			],
		];
	}

	public function actions() {
		return [
			'error'   => [
				'class' => 'yii\web\ErrorAction',
			],
			'captcha' => [
				'class'           => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST? 'testMe': null,
			],
		];
	}

	// INTRO

	public function actionIndex() {
		return $this->render('index');
	}

	public function actionCatalog() {
		return $this->render('catalog');
	}

	public function actionBenefits() {
		return $this->render('benefits');
	}

	public function actionWhatToKnow() {
		return $this->render('what-to-know');
	}

	public function actionAbout() {
		return $this->render('about');
	}

	public function actionHowWeWork() {
		return $this->render('how-we-work');
	}

	// KITCHENS

	public function actionKitchensPdf() {
		return $this->render('kitchens-pdf');
	}

	public function actionKitchensIntro() {
		return $this->render('kitchens-intro');
	}

	public function actionKitchensBenefits() {
		return $this->render('kitchens-benefits');
	}

	public function actionKitchensTv() {
		return $this->render('kitchens-tv');
	}

	public function actionKitchensMap() {
		return $this->render('kitchens-map');
	}

	// FURNITURE READY

	public function actionFurnitureReady() {
		return $this->render('furniture-ready');
	}

	public function actionFurnitureReadyAbout() {
		return $this->render('furniture-ready-about');
	}

	public function actionFurnitureReadyPaged() {
		return $this->render('furniture-ready-paged');
	}

	public function actionFurnitureReadyPagedAbout() {
		return $this->render('furniture-ready-paged-about');
	}

	public function actionFurnitureReadyCilek() {
		return $this->render('furniture-ready-cilek');
	}

	public function actionFurnitureReadyCilekAbout() {
		return $this->render('furniture-ready-cilek-about');
	}

	public function actionFurnitureReadyCilekMap() {
		return $this->render('furniture-ready-cilek-map');
	}

	public function actionFurnitureReadyCilekYears() {
		return $this->render('furniture-ready-cilek-years');
	}

	public function actionFurnitureReadyTctNanotec() {
		return $this->render('furniture-ready-tct-nanotec');
	}

	public function actionFurnitureOrder() {
		return $this->render('furniture-order');
	}

	public function actionFurnitureOrderAbout() {
		return $this->render('furniture-order-about');
	}

	public function actionSits() {
		return $this->render('sits');
	}

	public function actionSitsAbout() {
		return $this->render('sits-about');
	}

	// INFO PAGES

	public function actionContacts() {
		return $this->render('contacts');
	}

	public function actionSampleSales() {
		return $this->render('sample-sales');
	}

	public function actionWholesale() {

		$mailSuccess = null;

		if (Yii::$app->request->isPost) {
			$params = Yii::$app->request->post();

			$mailSuccess = Yii::$app->mailer
				->compose('@views/mail/common', [
					'name'    => $params['name'],
					'phone'   => $params['phone'],
					'comment' => $params['comment'],
				])
				->attach($_FILES['file']['tmp_name'], ['fileName' => $_FILES['file']['name']])
				->setFrom(Yii::$app->params['emailFrom'])
				->setTo(Yii::$app->params['emailTo'])
				->setSubject('Заказ звонка с сайта ' . Yii::$app->name)
				->send();
		}

		return $this->render('wholesale', ['mailSuccess' => $mailSuccess]);
	}

	public function actionDesigners() {
		return $this->render('designers');
	}

	public function actionDreamJob() {
		return $this->render('dream-job');
	}

	public function actionActions() {
		return $this->render('actions');
	}

	public function actionCredit() {
		return $this->render('credit');
	}
}

views/main/actions.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Url;
use yii\helpers\Html;

$this->title = 'Сгостиные, детские, спальни по цене, напрямую  от производителя';
?>

<script>
	document.body.className = 'light-body';
</script>

<style>
	body {
		background-color: #f0f3f8;
	}
</style>

<ul class="actions__nav">
	<li class="active">
		<a data-toggle="tab" href="#tv" class="text-horizontal-arrow">
			Телевизор в&nbsp;подарок
			<span class="arrowed-link__arrow arrowed-link__arrow_left"></span>
		</a>
	</li>
	<li>
		<a data-toggle="tab" href="#fridge" class="text-horizontal-arrow">
			Встраиваемый холодильник в&nbsp;подарок
			<span class="arrowed-link__arrow arrowed-link__arrow_left"></span>
		</a>
	</li>
	<li>
		<a data-toggle="tab" href="#dish-washer" class="text-horizontal-arrow">
			Встраиваемая посудомоечная машина в&nbsp;подарок
			<span class="arrowed-link__arrow arrowed-link__arrow_left"></span>
		</a>
	</li>
</ul>

<div class="row h100">
	<div class="col-sm-offset-2 col-sm-8 h100" style="overflow: hidden;">
		<h1 class="title-benefits title-benefits_violet">Сгостиные, детские, спальни
			<span class="yellow-bg">по&nbsp;цене, напрямую</span> от&nbsp;производителя</h1>

		<p class="t-C">При покупке мебели VOX, Paged, Glek, Flippy Grandy.</p>

		<div class="tab-content t-C">
			<div class="tab-pane active" id="tv">
				<div class="actions__title">
					<span class="actions__title-tail"></span>
					<span class="actions__title-tail actions__title-tail_right"></span>
					Телевизор в&nbsp;подарок
				</div>

				<div class="t-C">
					<img class="actions__img" src="/images/tv-big-action.png" alt="">
				</div>

				<p>Телевизор LG. Новинка 2015 года!</p>
			</div>
			<div class="tab-pane" id="fridge">
				<div class="actions__title">
					<span class="actions__title-tail"></span>
					<span class="actions__title-tail actions__title-tail_right"></span>
					Холодильник в&nbsp;подарок
				</div>

				<div class="t-C">
					<img class="actions__img" src="/images/ice-big-action.png" alt="">
				</div>

				<p>Холодильник LG. Новинка 2015 года!</p>
			</div>
			<div class="tab-pane" id="dish-washer">
				<div class="actions__title">
					<span class="actions__title-tail"></span>
					<span class="actions__title-tail actions__title-tail_right"></span>
					Посудомойка в&nbsp;подарок
				</div>

				<div class="t-C">
					<img class="actions__img" src="/images/wash-big-action.png" alt="">
				</div>

				<p>Посудомоечная машина LG. Новинка 2015 года!</p>
			</div>
		</div>

		<div class="main-menu__credit actions__credit">
			<i></i>
			<a href="<?= Url::to(['main/credit']) ?>">Действует рассрочка от&nbsp;салона «Forms»</a>
		</div>

		<p class="t-C">подробности по&nbsp;телефону +7&nbsp;423 20 90&nbsp;999 или у&nbsp;сотрудников салона</p>
	</div>

	<?= $this->render('@parts/button-back') ?>
</div>

views/main/catalog.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Url;

$this->title = 'Новый формат мебельных магазинов';
?>

<?= $this->render('@parts/pagination-intro', [
	'active' => 2,
]) ?>

<style>
	.logo {
		display: none;
	}
</style>

<script>
	document.body.className = 'light-body';
</script>

<div class="row h100 catalog padding-top-mobile">
	<div class="col-sm-6 h100">
		<div class="catalog__h33 catalog__kitchen">
			<div class="catalog__inner">
				<h1 class="title">Кухни</h1>
			</div>

			<div class="catalog__pin-to-bottom">
				<a href="<?= Url::to(['main/kitchens-pdf']) ?>" class="text-horizontal-arrow">
					<span class="arrowed-link__arrow arrowed-link__arrow_right"></span>
					Комплексные интерьерные решения для всей семьи
				</a>
			</div>
		</div>
		<div class="catalog__h33 catalog__furniture-ready">
			<div class="catalog__inner">
				<h1 class="title">Корпусная мебель</h1>

				<div class="catalog__desc">(гостиные, детские, гардеробные, спальни)</div>
				<div class="catalog__desc-2">Готовые</div>

				<div class="catalog__pin-to-bottom">
					<a href="<?= Url::to(['main/furniture-ready']) ?>" class="text-horizontal-arrow">
						<span class="arrowed-link__arrow arrowed-link__arrow_right"></span>
						Комплексные интерьерные решения для всей семьи
					</a>
				</div>
			</div>
		</div>
		<div class="catalog__h33 catalog__furniture-order">
			<div class="catalog__inner">
				<h1 class="title">Корпусная мебель</h1>

				<div class="catalog__desc">(гостиные, детские, гардеробные, спальни)</div>
				<div class="catalog__desc-2">На заказ</div>

				<div class="catalog__pin-to-bottom">
					<a href="<?= Url::to(['main/furniture-order']) ?>" class="text-horizontal-arrow">
						<span class="arrowed-link__arrow arrowed-link__arrow_right"></span>
						Комплексные интерьерные решения для всей семьи
					</a>
				</div>
			</div>
		</div>
	</div>
	<div class="col-sm-6 h100">
		<div class="catalog__right-center">
			<i class="logo-big"></i>
			<h2 class="catalog-title"><?= $this->title ?></h2>

			<p>Наша миссия&nbsp;&mdash; дать людям красивую и&nbsp;качественную мебель по&nbsp;справедливой цене. Мы&nbsp;стремимся
				не&nbsp;просто продать и&nbsp;забыть, а&nbsp;помочь выбрать, подсказать, как лучше. Даже если лучше&nbsp;&mdash;
				это дешевле, даже если лучше&nbsp;&mdash; это меньше, но&nbsp;все&nbsp;же лучше.</p>
		</div>

<!--		<div class="catalog__in-bottom">-->
		<div class="pin-to-bottom pin-to-bottom_w50">
			<a href="<?= Url::to(['main/benefits']) ?>" class="text-horizontal-arrow text-horizontal-arrow_violet uc">
				<span class="arrowed-link__arrow"></span>
				Почему Forms?
			</a>
			<?= $this->render('@parts/order-fitting') ?>
		</div>
	</div>
</div>

views/main/furniture-ready-about.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Url;
use yii\helpers\Html;

$this->title = 'Корпусная мебель: Изучай, Твори, Смотри';
?>

<?= $this->render('@parts/furniture-ready') ?>

<script>
	document.body.className = 'furniture-ready__bg-brown hide-logo';
</script>

<div class="row h100 padding-top-mobile">
	<div class="col-sm-6 h100">
		<div class="expand-to-gutters">
			<div id="carousel-generic" class="carousel slide" data-ride="carousel">
				<!-- Wrapper for slides -->
				<div class="carousel-inner" role="listbox">
					<div class="item active">
						<img src="/images/salon-bg.png" alt="">
					</div>
					<div class="item">
						<img src="/images/kitchen.png" alt="">
					</div>
				</div>

				<!-- Controls -->
				<a class="carousel-nav carousel-nav_left" href="#carousel-generic" role="button" data-slide="prev">
				</a>
				<a class="carousel-nav" href="#carousel-generic" role="button" data-slide="next">
				</a>
			</div>
		</div>

		<div class="kitchens-intro__choose white h50">
			<h3>Выберите кухню сейчас</h3>
			<p>Оставьте свой номер телефона и&nbsp;в&nbsp;ближайшее время с&nbsp;вами свяжется наш специалист, который поможет составить дизайн вашей будущей кухни в&nbsp;удобное для вас время совершенно бесплатно!</p>

			<?= $this->render('@parts/form-callback', ['style' => 'white']) ?>
		</div>
	</div>
	<div class="col-sm-6 block-padding-top h100">
		<h1 class="furniture-ready__title"><?= $this->title ?></h1>

		<ul class="list">
			<li>Более 25 лет на&nbsp;рынке</li>
			<li>Продается в&nbsp;36 странах</li>
			<li>Каждая из&nbsp;коллеций создана известным дизайнером</li>
			<li>VOX- фанаты творчества, дизайна, <nobr>ноу-хау</nobr></li>
			<li>Вся продукция соответствует европейскому классу гигиеничности Е1</li>
			<li>Визуализация&nbsp;&mdash; возможность создания в&nbsp;салоне интерьера любой комнаты (спальни, гостиные, детские) с&nbsp;нуля</li>
		</ul>

		<div class="furniture-ready__ok">
			Высококачаственное ЛДСП, которое характеризуется очень высокой стойкостью к&nbsp;повреждениям, воздействию высокой температуры и&nbsp;влаги
		</div>

		<div class="pin-to-bottom pin-to-bottom_w50">
			<a href="<?= Url::to(['main/furniture-ready-paged']) ?>" class="text-horizontal-arrow uc">
				<span class="arrowed-link__arrow"></span>
				Готовые решения Paged
			</a>
			<?= $this->render('@parts/order-fitting') ?>
		</div>
	</div>
</div>

views/main/furniture-ready-cilek-about.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Url;
use yii\helpers\Html;

$this->title = 'Корпусная мебель: Готовые решения';
?>

<?= $this->render('@parts/pagination-furniture-ready-cilek') ?>

<script>
	document.body.className = 'furniture-ready__bg-brown hide-logo';
</script>

<div class="row furniture-ready-cilek h100">
	<div class="col-sm-6 h100">
		<div class="h50 expand-to-gutters">
			<div id="carousel-generic" class="carousel slide" data-ride="carousel">
				<!-- Wrapper for slides -->
				<div class="carousel-inner" role="listbox">
					<div class="item active">
						<img src="/images/salon-bg.png" alt="">
					</div>
					<div class="item">
						<img src="/images/kitchen.png" alt="">
					</div>
				</div>

				<!-- Controls -->
				<a class="carousel-nav carousel-nav_left" href="#carousel-generic" role="button" data-slide="prev">
				</a>
				<a class="carousel-nav" href="#carousel-generic" role="button" data-slide="next">
				</a>
			</div>
		</div>

		<div class="kitchens-intro__choose white h50">
			<h3>Выберите креативную комнату <br>для вашего ребенка сейчас</h3>
			<p>Оставьте свой номер телефона и&nbsp;в&nbsp;ближайшее время с&nbsp;вами свяжется наш специалист, который поможет составить дизайн вашей будущей кухни в&nbsp;удобное для вас время совершенно бесплатно!</p>

			<?= $this->render('@parts/form-callback', ['style' => 'white']) ?>
		</div>
	</div>
	<div class="col-sm-6 block-padding-top h100">
		<h1 class="furniture-ready-cilek__title">
			<?= $this->title ?>
			<span class="furniture-ready-cilek__desc">(детские)</span>
		</h1>

		<ul class="list">
			<li>Продается на&nbsp;5 континентах. В&nbsp;66 странах. 444 торговые точки</li>
			<li>Начиная с&nbsp;1995 года, фабрика занимается производством детской мебели&nbsp;&mdash; это единственная из&nbsp;компаний на&nbsp;мировом рынке, которая специализированно занимается производством только детской мебели</li>
			<li>Мебель соотвествует стандартам CE, E1, TUV, GS, LGA, LSA, RoHS, Confidense in&nbsp;Textile, Ростест</li>
		</ul>

		<div class="furniture-ready__ok">
			На&nbsp;фабрике работает специальная <nobr>&laquo;Креатив-Студия&raquo;</nobr>, занимающаяся разработкой дизайна, учитывающего психологические особенности ребенка и&nbsp;его безопасность
		</div>

		<div class="pin-to-bottom pin-to-bottom_w50">
			<a href="<?= Url::to(['main/furniture-ready-cilek-map']) ?>" class="text-horizontal-arrow uc">
				<span class="arrowed-link__arrow"></span>
				Особенности мебели
			</a>
			<?= $this->render('@parts/order-fitting') ?>
		</div>
	</div>
</div>

views/main/furniture-ready-cilek.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Url;

$this->title = 'Корпусная мебель:<br> готовые решения';
?>

<?= $this->render('@parts/pagination-furniture-ready-cilek') ?>

<script>
	document.body.className = 'furniture-ready-cilek__bg';
</script>

<h1 class="title-benefits"><?= $this->title ?></h1>

<div class="furniture-ready__desc t-C">
	(детская мебель)
</div>

<div class="row">
	<div class="col-sm-offset-4 col-sm-4 t-C">
		<a href="<?= Url::to(['pdf/cilek']) ?>" target="_blank" class="kitchens__pdf-links" data-disable-ajax>
			<img src="/images/cilek-pdf.png" alt="">
			<span>Каталог мебели CILEK</span>
		</a>
	</div>
</div>

<div class="arrowed-link pin-to-bottom margin-bottom">
	<a class="arrowed-link__link" href="<?= Url::to(['main/furniture-ready-cilek-about']) ?>">
		<span class="arrowed-link__text">Мебель CILEK</span>
		<span class="arrowed-link__arrow"></span>
	</a>
	<?= $this->render('@parts/order-fitting') ?>
</div>

views/main/furniture-ready-paged-about.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Url;
use yii\helpers\Html;

$this->title = 'Корпусная мебель: Готовые решения';
?>

<?= $this->render('@parts/furniture-ready-paged') ?>

<script>
	document.body.className = 'furniture-ready__bg-brown-light hide-logo light-brown-body';
</script>

<div class="row furniture-ready-paged h100">
	<div class="col-sm-6 h100">
		<div class="h50 expand-to-gutters">
			<div id="carousel-generic" class="carousel slide" data-ride="carousel">
				<!-- Wrapper for slides -->
				<div class="carousel-inner" role="listbox">
					<div class="item active">
						<img src="/images/salon-bg.png" alt="">
					</div>
					<div class="item">
						<img src="/images/kitchen.png" alt="">
					</div>
				</div>

				<!-- Controls -->
				<a class="carousel-nav carousel-nav_left" href="#carousel-generic" role="button" data-slide="prev">
				</a>
				<a class="carousel-nav" href="#carousel-generic" role="button" data-slide="next">
				</a>
			</div>
		</div>

		<div class="kitchens-intro__choose h50">
			<h3>Выберите мебель сейчас</h3>
			<p>Оставьте свой номер телефона и&nbsp;в&nbsp;ближайшее время с&nbsp;вами свяжется наш специалист, который поможет составить дизайн вашей будущей кухни в&nbsp;удобное для вас время совершенно бесплатно!</p>

			<?= $this->render('@parts/form-callback', ['style' => 'brown']) ?>
		</div>
	</div>
	<div class="col-sm-6 block-padding-top h100">
		<h1 class="furniture-ready-paged__title"><?= $this->title ?></h1>
		<span class="furniture-ready-paged__desc">(гостиные, спальни, гардеробные, детские)</span>

		<ul class="list list_brown">
			<li>История Paged началась с&nbsp;1881 года, с&nbsp;небольшого производства мебели из&nbsp;гнутого дерева, извесной под названием &laquo;Венские стулья&raquo;</li>
			<li>Инновационная технология изгиба древесины с&nbsp;помощью особой гидротехнической обработки&nbsp;&mdash; &laquo;визитная карточка&raquo; Paged</li>
			<li>Мебель Paged можно встретить в&nbsp;лучших домах и&nbsp;квартирах, практически всего мира&nbsp;&mdash; Великобритании, Голландии, США, Японии, Германии и&nbsp;других стран</li>
		</ul>

		<div class="pin-to-bottom pin-to-bottom_w50">
			<a href="<?= Url::to(['main/furniture-ready-cilek']) ?>" class="text-horizontal-arrow text-horizontal-arrow_brown uc">
				<span class="arrowed-link__arrow"></span>
				Готовые решения Cilek
			</a>
			<?= $this->render('@parts/order-fitting') ?>
		</div>
	</div>
</div>

views/main/furniture-ready-paged.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Url;

$this->title = 'Корпусная мебель:<br> готовые решения';
?>

<?= $this->render('@parts/furniture-ready-paged') ?>

<script>
	document.body.className = 'furniture-ready-paged__bg';
</script>

<h1 class="title-benefits"><?= $this->title ?></h1>

<div class="furniture-ready__desc t-C">
	(массив натурального дерева)
</div>

<div class="row">
	<div class="col-sm-offset-1 col-sm-5 t-C">
		<a href="<?= Url::to(['pdf/paged-1']) ?>" target="_blank" class="kitchens__pdf-links" data-disable-ajax>
			<img src="/images/paged-pdf1.png" alt="">
			<span>Каталог мебели PAGED</span>
		</a>
	</div>
	<div class="col-sm-5 t-C">
		<a href="<?= Url::to(['pdf/paged-2']) ?>" target="_blank" class="kitchens__pdf-links" data-disable-ajax>
			<img src="/images/paged-pdf2.png" alt="">
			<span>Каталог столов и стульев PAGED</span>
		</a>
	</div>
</div>

<div class="arrowed-link pin-to-bottom margin-bottom">
	<a class="arrowed-link__link" href="<?= Url::to(['main/furniture-ready-paged-about']) ?>">
		<span class="arrowed-link__text">Мебель Paged</span>
		<span class="arrowed-link__arrow"></span>
	</a>
	<?= $this->render('@parts/order-fitting') ?>
</div>

views/main/furniture-ready.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Url;

$this->title = 'Корпусная мебель:<br> готовые решения';
?>

<?= $this->render('@parts/furniture-ready') ?>

<script>
	document.body.className = 'furniture-ready__bg';
</script>

<h1 class="title-benefits"><?= $this->title ?></h1>

<div class="furniture-ready__desc t-C">
	(гостиные, спальни, гардеробные, детские)
</div>

<div class="row">
	<div class="col-sm-offset-4 col-sm-4 t-C">
		<a href="<?= Url::to(['pdf/vox']) ?>" target="_blank" class="kitchens__pdf-links" data-disable-ajax>
			<img src="/images/vox-pdf.png" alt="">
			<span>Каталог мебели VOX</span>
		</a>
	</div>
</div>

<div class="arrowed-link pin-to-bottom margin-bottom">
	<a class="arrowed-link__link" href="<?= Url::to(['main/furniture-ready-about']) ?>">
		<span class="arrowed-link__text">Мебель VOX</span>
		<span class="arrowed-link__arrow"></span>
	</a>
	<?= $this->render('@parts/order-fitting') ?>
</div>

views/main/kitchens-map.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Url;
use yii\helpers\Html;

$this->title = 'Выпуски телепередач';
?>

<?= $this->render('@parts/pagination-kitchens') ?>

<script>
	document.body.className = 'light-body';
</script>

<div class="js-kitchen-map kitchen-map">
	<div class="map-pin kitchen-map__1"
		 title="<div class='tooltip-header'>Фасады</div> Массив дерева&nbsp;&mdash; три ведущих итальянских производителя Stival, ILCAM, Mobilclan"></div>
	<div class="map-pin kitchen-map__2"
		title="<div class='tooltip-header'>Пленка ПВХ</div> от 0,4 до 0,75 мм, более тягучая, что обеспечивает плотное прилегание. Наносится путем вакуумного пресования. Применяется в пищевой"></div>
	<div class="map-pin kitchen-map__3"
		title="<div class='tooltip-header'>ЛДСП 18 мм EGGER</div> Австрия высокая плотность плиты, нет выделений формальдегида"></div>
	<div class="map-pin kitchen-map__4"
		title="<div class='tooltip-header'>Глубина верхних шкафов - 35 см</div> Это дает возможность разместить два чайных набора в глубину"></div>
	<div class="map-pin kitchen-map__5"
		title="<div class='tooltip-header'>Ручки</div> Только металл т стекло, никакого пластика. Безопасная - завальцовка"></div>
	<div class="map-pin kitchen-map__6"
		title="<div class='tooltip-header'>Кромка</div> 1 мм Евростандарт: плотное прилегание, не отслаивается, наностится автоматически, в отличие от кромки 0,4 мм, которую приклеивают утюгом"></div>
	<div class="map-pin kitchen-map__7"
		 title="<div class='tooltip-header'>Фартук</div> В цвет столешницы - 8-10 мм"></div>
	<div class="map-pin kitchen-map__8"
		title="<div class='tooltip-header'>Фурнитура</div> Hettich(Германия) и Blum(Австрия): 25 лет гарантии, крючки навески выдерживают до 90 килограмм, в отличе от других производителей, максимальная нагрузка, на которые на 15 килограмм меньше"></div>
	<div class="map-pin kitchen-map__9"
		title="<div class='tooltip-header'>Эстетика</div> нет самоклеящихся заглушек скрывающих винты"></div>
	<div class="map-pin kitchen-map__10"
		title="<div class='tooltip-header'>Алюминиевая подложка под мойкой</div> Защита днища стола от протечек"></div>
	<div class="map-pin kitchen-map__11"
		title="<div class='tooltip-header'>Врезная задняя стенка</div> Вставляется в специально пропиленые пазы"></div>
	<div class="map-pin kitchen-map__12"
		title="<div class='tooltip-header'>Цоколь</div> Пластиковый с силиконовым уплотнителем. В классических кухнях из массива - шпонированый"></div>
</div>

<div class="arrowed-link pin-to-bottom margin-bottom">
	<a class="arrowed-link__link text-horizontal-arrow_violet" href="<?= Url::to(['main/furniture-ready']) ?>">
		<span class="arrowed-link__text">Корпусная мебель</span>
		<span class="arrowed-link__arrow"></span>
	</a>
	<?= $this->render('@parts/order-fitting') ?>
</div>

views/main/kitchens-pdf.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Url;

$this->title = 'Кухни Forms';
?>

<?= $this->render('@parts/pagination-kitchens') ?>

<script>
	document.body.className = 'kitchens__bg';
</script>

<h1 class="title-benefits"><?= $this->title ?></h1>

<div class="kitchens__folio-insta">
	<a href="<?= Yii::$app->params['instagramLink'] ?>" target="_blank">
		Наши работы в Instagramm
	</a>
</div>

<div class="row">
	<div class="col-sm-4 t-C">
		<a href="<?= Url::to(['pdf/orange']) ?>" target="_blank" class="kitchens__pdf-links" data-disable-ajax>
			<img src="/images/orange.png" alt="">
			<span>Оранжевая коллекция <br>
			Современные кухни</span>
		</a>
	</div>
	<div class="col-sm-4 t-C">
		<a href="<?= Url::to(['pdf/silver']) ?>" target="_blank" class="kitchens__pdf-links" data-disable-ajax>
			<img src="/images/silver.png" alt="">
			<span>Серебрянная коллекция <br>
			Уникальные кухни</span>
		</a>
	</div>
	<div class="col-sm-4 t-C">
		<a href="<?= Url::to(['pdf/white']) ?>" target="_blank" class="kitchens__pdf-links" data-disable-ajax>
			<img src="/images/white.png" alt="">
			<span>Белая коллекция <br>
			Классические кухни</span>
		</a>
	</div>
</div>

<div class="arrowed-link pin-to-bottom margin-bottom">
	<a class="arrowed-link__link" href="<?= Url::to(['main/kitchens-intro']) ?>">
		<span class="arrowed-link__text">Кухни Forms</span>
		<span class="arrowed-link__arrow"></span>
	</a>
	<?= $this->render('@parts/order-fitting') ?>
</div>